language: node_js
git:
  autocrlf: true
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 14
script:
  - npm run test
  - npm run lint
  - npm run build
after_success:
  - npm run report-coverage
