title: Punch UI
email: m.tutynina@list.ru
description: >-
  Punch UI is simple components library based on KnockoutJS and Bootstrap 5.
baseurl: "punch-ui"
# url: "https://mtutynina.github.io/punch-ui"
github_username:  mtutynina

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: "default"
search_enabled: false
aux_links:
  "GitHub":
    - "//github.com/mtutynina/punch-ui"

aux_links_new_tab: true

exclude:
 - Gemfile
 - Gemfile.lock
